<?php

namespace AppBundle\Repository;

/**
 * BabyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BabyRepository extends \Doctrine\ORM\EntityRepository
{
}
